### ISSUE TITLE
unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by alaney2** [ncbi-nlp/TrialGPT#2]
When running this command 
```
python trialgpt_retrieval/keyword_generation.py sigir gpt-4-turbo
```
I am getting an error:
```
Traceback (most recent call last):
  File "/Users/alaney2/Documents/TrialGPT/trialgpt_retrieval/keyword_generation.py", line 17, in <module>
    client = AzureOpenAI(
  File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/lib/azure.py", line 207, in __init__
    super().__init__(
  File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/_client.py", line 122, in __init__
    super().__init__(
  File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 825, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
  File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 723, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
```

any idea why? I have set up the env variables by exporting them and with a ```.env``` file

**Comment by drqiaojin** [comment]
> When running this command
> 
> ```
> python trialgpt_retrieval/keyword_generation.py sigir gpt-4-turbo
> ```
> 
> I am getting an error:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/alaney2/Documents/TrialGPT/trialgpt_retrieval/keyword_generation.py", line 17, in <module>
>     client = AzureOpenAI(
>   File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/lib/azure.py", line 207, in __init__
>     super().__init__(
>   File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/_client.py", line 122, in __init__
>     super().__init__(
>   File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 825, in __init__
>     self._client = http_client or SyncHttpxClientWrapper(
>   File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 723, in __init__
>     super().__init__(**kwargs)
> TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
> ```
> 
> any idea why? I have set up the env variables by exporting them and with a `.env` file

It seems that the bug is caused by API calling. Could you show the exact code snippets?

**Comment by alaney2** [comment]
I was able to resolve this error with the latest openai package, there was an issue with the httpx version. However now I am getting a different error 

```
~/Documents/TrialGPT (main ✘)✹✭ ᐅ python trialgpt_retrieval/keyword_generation.py sigir gpt-4-turbo

Traceback (most recent call last):
  File "/Users/alaney2/Documents/TrialGPT/trialgpt_retrieval/keyword_generation.py", line 52, in <module>
    response = client.chat.completions.create(
  File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 859, in create
    return self._post(
  File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1280, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 957, in request
    return self._request(
  File "/Users/alaney2/Documents/TrialGPT/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1061, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}
```

Even with the OPENAI_API_KEY and OPENAI_ENDPOINT in my ```.env``` file and exported in the terminal, I am getting this

**Comment by alaney2** [comment]
was able to fix the bug by upgrading to the latest openai package, i think there was some issue in httpx that it solved
